version: '3.8'

services:
  # Redis for caching (optional but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: stem-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stem-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stem-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://82.197.82.136:3306/u934701285_stem
      SPRING_DATASOURCE_USERNAME: u934701285_stem_user
      SPRING_DATASOURCE_PASSWORD: T9LvG/4&zc2.2Xc
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - stem-network
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # Reduced startup delay since we're using external database
    command: >
      sh -c "
        echo 'Starting application with external database...' &&
        sleep 10 &&
        java -jar app.jar
      "

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: stem-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - stem-network

networks:
  stem-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  app_logs:
    driver: local
  nginx_logs:
    driver: local